let g:powerline_pycmd = 'py3'
set laststatus=2 " Always display the statusline in all windows
set showtabline=2 " Always display the tabline, even if there is only one tab
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
set t_Co=256
syntax on
let $EX_DEV='/usr/share/exvim' " Generated by exVim
let g:ex_toolkit_path = $EX_DEV.'/tools' " Generated by exVim 
