#!/bin/sh

# /etc/init.d/vpn-unlimited-daemon

### BEGIN INIT INFO
# Provides:          vpn-unlimited-daemon
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Should-Start:      network-manager
# Should-Stop:       network-manager
# X-Start-Before:    $x-display-manager gdm kdm xdm wdm ldm sdm nodm
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raise VPNUnlimited service daemon
# Description:       Raise VPNUnlimited service daemon
### END INIT INFO

. /lib/lsb/init-functions

[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PROGRAM=/usr/bin/vpn-unlimited-daemon

test -x $PROGRAM || exit 0

case "$1" in
  start)
    log_begin_msg "Start VPNUnlimited daemon\n"
    start-stop-daemon -Sbvx $PROGRAM
    log_end_msg 0
    ;;
  stop)
    log_begin_msg "Stop VPNUnlimited daemon\n"
    start-stop-daemon -Kvx $PROGRAM
    log_end_msg 0
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    if test -z `pidof $PROGRAM` ; then
        log_failure_msg "VPNUnlimited daemon is not running"
    else
        port=`cat /var/run/vpn_unlimited_service`
        log_success_msg "VPNUnlimited daemon run on $port port"
    fi
    exit 0
    ;;
  *)
    log_success_msg "Usage: $PROGRAM {start|stop|restart|force-reload|status}"
    exit 1
esac

exit 0
